"""
Django settings for Backend_PortfolioX project.

Generated by 'django-admin startproject' using Django 4.2.25.
"""

from pathlib import Path
from datetime import timedelta  # AJOUT: Pour la configuration JWT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-96^tc_zpr3)1vc=)!8*jpsortkgac4&)+ltvp3%-c65)75_eh$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
     # Applications tierces  # CORRECTION: "tierces" pas "tirons"
    'rest_framework',
    'rest_framework_simplejwt',  # AJOUT: Pour JWT
    'corsheaders',  # AJOUT: Pour CORS
    'django_filters',  # AJOUT: Pour le filtrage
    
    # Applications locales
    'utilisateur',
    'portfolio',
]  # CORRECTION: Virgule ajoutée

# Configuration de l'authentification personnalisée
AUTH_USER_MODEL = 'utilisateur.Utilisateur'  # CORRECTION: "MODEL" pas "MODÈLE" et "Utilisateur" majuscule

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # AJOUT: Doit être en premier
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Backend_PortfolioX.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Backend_PortfolioX.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Configuration Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# Configuration Simple JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # AJOUT: Durée de vie du token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # AJOUT: Durée de vie du refresh token
    'ROTATE_REFRESH_TOKENS': True,  # AJOUT: Rotation des tokens
    'BLACKLIST_AFTER_ROTATION': True,  # DÉJÀ PRÉSENT
    'UPDATE_LAST_LOGIN': True,  # AJOUT: Met à jour last_login
    'AUTH_HEADER_TYPES': ('Bearer',),  # AJOUT: Type de header
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration CORS
CORS_ALLOW_ALL_ORIGINS = True  # DÉJÀ PRÉSENT