# Generated by Django 4.2.25 on 2025-11-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id_competence', models.AutoField(primary_key=True, serialize=False)),
                ('nom_competence', models.CharField(max_length=100)),
                ('niveau_competence', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_contact', models.AutoField(primary_key=True, serialize=False)),
                ('type_contact', models.CharField(choices=[('email', 'Email'), ('telephone', 'Téléphone'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter'), ('autre', 'Autre')], max_length=20)),
                ('valeur_contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id_projet', models.AutoField(primary_key=True, serialize=False)),
                ('titre_projet', models.CharField(max_length=200)),
                ('description_projet', models.TextField()),
                ('langage_projet', models.CharField(max_length=100)),
                ('lien_projet', models.URLField(blank=True, null=True)),
                ('image_projet', models.ImageField(blank=True, null=True, upload_to='projets/')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id_template', models.AutoField(primary_key=True, serialize=False)),
                ('nom_template', models.CharField(max_length=100)),
                ('description_template', models.TextField()),
                ('fichier_html', models.FileField(upload_to='templates/')),
                ('image_template', models.ImageField(blank=True, null=True, upload_to='templates_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id_portfolio', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('competences', models.ManyToManyField(blank=True, to='portfolio.competence')),
                ('contacts', models.ManyToManyField(blank=True, to='portfolio.contact')),
                ('projets', models.ManyToManyField(blank=True, to='portfolio.projet')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.template')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur')),
            ],
        ),
    ]
